APT::FTPArchive::Release::Origin "Tomas Larsson";
APT::FTPArchive::Release::Label "Scarpa Connection Manager";
APT::FTPArchive::Release::Suite "stable";
APT::FTPArchive::Release::Codename "stable";
APT::FTPArchive::Release::Architectures "amd64 all";
APT::FTPArchive::Release::Components "main";
APT::FTPArchive::Release::Description "Scarpa Connection Manager Repository";
