name: connection-manager-scarpa
base: core22                           
version: '1.2.22-20'
summary: A slimmed down SSH/SFTP client and connection manager including a SFTP GUI
description: |
  **SCARPA Connection Manager**  is a SSH client desktop application designed for sysadmins, developers, and power users who need to logically organize and securely manage hundreds of remote servers.
  
  **Core Features:**
  
  * **Server & Folder Management:** Organize servers hierarchically. Supports drag-and-drop reordering, inline renaming, and quick copy/paste via keyboard shortcuts.
  * **Embedded VTE Terminal:** Features smart copy/paste, auto-resize sync with the remote host, and support for advanced port forwarding (Local, Remote, Dynamic).
  * **Connection Automation:** Automate login sequences with built-in Expect/Send steps (with passwords hidden in the UI), or authenticate securely using standard key files.
  * **Dual-Pane SFTP Manager:** Visually manage files between your local machine and remote servers side-by-side. Supports drag-and-drop, recursive search, smart transfer resuming, and real-time status updates.
  * **"Super Safe" Encryption:** All server configurations and credentials are encrypted at rest using AES256 via GnuPG. Your master passphrase is heavily hashed (PBKDF2-HMAC-SHA256), and data is only decrypted in memory during active sessions.
  * **Customization:** Set global defaults or customize the font, color palette (Tango, Solarized, etc.), and scrollback buffer on a per-server basis.
  * **Data Portability:** Easily export and import your configurations as either plaintext JSON or encrypted GPG files.
  
  A GTK-based SSH/SFTP session manager.
  Riposa in pace, Aquila di Filottrano. Sarai sempre con noi!

icon: data/icons/hicolor/512x512/apps/scarpa_icon.png

grade: stable
confinement: strict 

apps:
  connection-manager-scarpa:   
    command: src/scarpa_connection_manager.py
    extensions: [gnome]
    desktop: data/snap_desktop.desktop
    plugs:
      - network
      - home
      - ssh-keys
      - ssh-public-keys
      - password-manager-service
      - removable-media
    environment:
      PYTHONPATH: $SNAP/usr/lib/python3/dist-packages:$PYTHONPATH

layout:
  /usr/share/scarpa_connection_manager:
    bind: $SNAP/usr/share/scarpa_connection_manager
    
  /usr/share/tcltk:
    bind: $SNAP/usr/share/tcltk

parts:
  scarpa:
    plugin: dump
    source: .
    stage-packages:
      - python3
      - python3-gi
      - gir1.2-gtk-3.0
      - gir1.2-vte-2.91
      - python3-paramiko
      - gnupg1                         
      - expect
      - openssh-client
      - tcl
      
    organize:
      data/icons/hicolor/: usr/share/icons/hicolor/
      docs/folder.png: usr/share/scarpa_connection_manager/folder.png
      docs/server.png: usr/share/scarpa_connection_manager/server.png
      docs/user_guide.html: usr/share/scarpa_connection_manager/user_guide.html
